### ISSUE TITLE
brew install returning a 404

### ISSUE THREAD

**Issue by mcdwayne** [devops-kung-fu/hookz#96]
Issue: Tried to install hookz after seeing the presentation at GitKon. 

Here is my terminal output. 

ggshield ~ $brew tap devops-kung-fu/homebrew-tap
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 3 taps (hashicorp/tap, homebrew/core and homebrew/cask).
==> New Formulae
cbindgen        edencommon      fend            gebug           metview         sambamba
curlcpp         fastfetch       fred            iir1            mxnet           verovio
==> New Casks
battery                 diffusionbee            readdle-spark           tempbox

You have 14 outdated formulae installed.
You can upgrade them with brew upgrade
or list them with brew outdated.

==> Tapping devops-kung-fu/tap
Cloning into '/opt/homebrew/Library/Taps/devops-kung-fu/homebrew-tap'...
remote: Enumerating objects: 39, done.
remote: Counting objects: 100% (39/39), done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 39 (delta 20), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (39/39), 6.45 KiB | 6.45 MiB/s, done.
Resolving deltas: 100% (20/20), done.
Tapped 3 formulae (15 files, 15KB).
ggshield ~ $brew install devops-kung-fu/homebrew-tap/hookz
==> Downloading https://github.com/devops-kung-fu/hookz/releases/download/v2.4.2/hookz_2.4.2_dar
curl: (22) The requested URL returned error: 404                              

Error: hookz: Failed to download resource "hookz"
Download failed: https://github.com/devops-kung-fu/hookz/releases/download/v2.4.2/hookz_2.4.2_darwin_all.tar.gz
ggshield ~ $brew install devops-kung-fu/homebrew-tap/hookz
==> Downloading https://github.com/devops-kung-fu/hookz/releases/download/v2.4.2/hookz_2.4.2_dar
curl: (22) The requested URL returned error: 404                              

Error: hookz: Failed to download resource "hookz"
Download failed: https://github.com/devops-kung-fu/hookz/releases/download/v2.4.2/hookz_2.4.2_darwin_all.tar.gz

**Comment by SVendittelli** [comment]
I am also seeing this issue. Looks like it is trying to download `v2.4.2` when the latest release is `v2.4.1` on GitHub.

**Comment by SVendittelli** [comment]
It looks like the GitHub action for the release failed: https://github.com/devops-kung-fu/hookz/actions/runs/2806280815/jobs/4427552492

@djschleen could you have a look at this?
